name = "Multiviewer"
product-name = "Multiviewer"
identifier = "net.bambinito.multiviewer"
description = "An app to view multiple realtime video feeds"
publisher = "Alban Moreon"
authors = ["Alban Moreon"]
copyright = "© 2026 Alban Moreon"
version = "0.1.0"
category = "Video"

binaries = [{ path = "Multiviewer", main = true }]

file-associations = [
  { extensions = ["multiviewer"], name = "Multiviewer Project", role = "editor" }
]
