formats = ["nsis"]
icons = ["assets/appicon/windows/AppIcon.ico"]
resources = [
  "vendor/LICENSE.md",
  "assets/appicon/windows/AppIcon.ico",
  { src = "vendor/ndi/windows/sdk/Bin/x64/Processing.NDI.Lib.x64.dll", target = "Processing.NDI.Lib.x64.dll" },
  { src = "vendor/ndi/windows/sdk/Bin/x64/Processing.NDI.Lib.Licenses.txt", target = "Processing.NDI.Lib.Licenses.txt" },
]

[nsis]
appdata-paths = ["$LOCALAPPDATA/$IDENTIFIER"]
installer-icon = "assets/appicon/windows/AppIcon.ico"
