/* -LICENSE-START-
** Copyright (c) 2026 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation (the
** "Software") to use, reproduce, display, distribute, sub-license, execute,
** and transmit the Software, and to prepare derivative works of the Software,
** and to permit third-parties to whom the Software is furnished to do so, in
** accordance with:
**
** (1) if the Software is obtained from Blackmagic Design, the End User License
** Agreement for the Software Development Kit ("EULA") available at
** https://www.blackmagicdesign.com/EULA/DeckLinkSDK; or
**
** (2) if the Software is obtained from any third party, such licensing terms
** as notified by that third party,
**
** and all subject to the following:
**
** (3) the copyright notices in the Software and this entire statement,
** including the above license grant, this restriction and the following
** disclaimer, must be included in all copies of the Software, in whole or in
** part, and all derivative works of the Software, unless such copies or
** derivative works are solely in the form of machine-executable object code
** generated by a source language processor.
**
** (4) THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
**
** A copy of the Software is available free of charge at
** https://www.blackmagicdesign.com/desktopvideo_sdk under the EULA.
**
** -LICENSE-END-
*/

#pragma once

#include <cstring>
#include <string>

#ifdef _WIN32
#include <windows.h>
#include <combaseapi.h>
#include <objbase.h>
#include <oleauto.h>
#endif

#ifdef __APPLE__
#include <CoreFoundation/CoreFoundation.h>
#include <CoreFoundation/CFPlugInCOM.h>
#endif

#include <DeckLinkAPI.h>

#ifdef _WIN32
#define DECKLINK_DLSTRING_T BSTR
#endif

#ifdef __APPLE__
#define DECKLINK_DLSTRING_T CFStringRef
#endif

#if !defined(_WIN32) && !defined(__APPLE__)
#define DECKLINK_DLSTRING_T const char*
#endif

// Create an IDeckLinkIterator using the platform-specific factory.
HRESULT DecklinkCreateIterator(IDeckLinkIterator** iterator);

// Convert a DeckLink SDK string to a UTF-8 std::string.
std::string DecklinkStringToStd(DECKLINK_DLSTRING_T str);

// Free a DeckLink SDK string returned by the API.
void DecklinkStringFree(DECKLINK_DLSTRING_T str);

// Sleep for the given number of milliseconds.
void DecklinkSleepMs(uint32_t ms);

// Cross-platform boolean type for DeckLink API (Windows uses BOOL=int, others use bool).
#ifdef _WIN32
using DecklinkBool = BOOL;
#else
using DecklinkBool = bool;
#endif

// Compare two DeckLink REFIIDs.
bool DecklinkIIDEqual(REFIID a, REFIID b);

// Returns true if the given REFIID is IUnknown.
bool DecklinkIsIUnknownIID(REFIID iid);

extern "C" {
// Write the supported DeckLink API version (bmdDeckLinkAPIVersion) as a
// NUL-terminated UTF-8 string into `buf`. Returns bytes written excluding the
// NUL, or 0 when the version is unavailable (driver not installed).
int decklink_api_version(char* buf, int buf_len);
}

#ifdef _WIN32
// RAII COM initializer for threads that call into the DeckLink API.
class DecklinkComScope {
public:
    DecklinkComScope();
    ~DecklinkComScope();

    DecklinkComScope(const DecklinkComScope&) = delete;
    DecklinkComScope& operator=(const DecklinkComScope&) = delete;

private:
    bool initialized_;
};
#else
class DecklinkComScope {
public:
    DecklinkComScope() {}
    ~DecklinkComScope() {}

    DecklinkComScope(const DecklinkComScope&) = delete;
    DecklinkComScope& operator=(const DecklinkComScope&) = delete;
};
#endif
